version: '3.7'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: demo
      POSTGRES_PASSWORD: testing
    volumes:
      - ./postgres:/var/lib/postgresql/data